# Generated by Django 4.1.2 on 2022-11-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(to='dashboard.like'),
        ),
    ]
