# Generated by Django 4.1.2 on 2022-11-19 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_news_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='dashboard.comments'),
        ),
        migrations.AlterField(
            model_name='news',
            name='like',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.like'),
        ),
    ]
