# Generated by Django 4.1.2 on 2022-11-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_comments_parent_alter_news_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.region'),
        ),
    ]
