# Generated by Django 4.1.2 on 2022-11-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_news_slug_alter_user_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='province',
            new_name='address',
        ),
    ]
